### ISSUE TITLE
Some people are getting 404s when submitting data or logging in

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#185] opened 2017-05-09 13:06 UTC
E.g., at 1pm 9 May

>I’ve attempted to edit the information on your site but keep getting redirected to a place ("This is not the page you were looking for”) where I can’t enter the information. This is the page in question:
https://candidates.democracyclub.org.uk/person/25400/

and, at 9pm 8 May

>I am having difficulty in login - I have clicked on the link you sent me in your email asking if I am standing again (I am!) and it takes me to "This is not the page you were looking for" So I have tried logging in normally and get taken to "This is not the page you were looking for."

and, at 11pm 8 May

>I’m the Green Party candidate for North Herefordshire.  I tried to update your list online, but got sent to ‘this is not the page you are looking for’. [This would have been before this candidate existed, so presumably they were going via the North Herefordshire page at https://candidates.democracyclub.org.uk/election/parl.2017-06-08/post/WMC:E14000847/north-herefordshire (I've subsequently added her)]

(I assume "This is the not the page you were looking for." is our 404 page?)

**Comment by symroe** [comment] 2017-05-09 15:25
Someone hinted that they'd been redirected to `elections2.democracyclub.org.uk`, and that's in keeping with the error text in the bug reports:

https://elections.democracyclub.org.uk/asdasdasd shows "
This is not the page you were looking for.", but https://candidates.democracyclub.org.uk/asdasdasd doesn't.

I'll try to figure out why EE is taking over the hostname for this site.

**Comment by mhl** [comment] 2017-05-09 16:04
This sounds as if it's linked as well: https://github.com/DemocracyClub/yournextrepresentative/issues/180

**Comment by JoeMitchell** [comment] 2017-05-09 16:17
More related stuff, I think: 

![image](https://cloud.githubusercontent.com/assets/8096305/25861003/5230bf7e-34db-11e7-9a4b-07b45ef3e8d7.png)

**Comment by JoeMitchell** [comment] 2017-05-09 16:21
Similarly, 

>I'm trying to sign up for my constituency but when I log in to Democracy Club Candidates I don't see any username appearing anywhere... 

![image](https://cloud.githubusercontent.com/assets/8096305/25861186/dc319a4a-34db-11e7-995b-cbfb2c80bb6a.png)

**Comment by symroe** [comment] 2018-03-20 08:27
I reckon this was a dupe of #180, and fixed now

**Closed by symroe** 2018-03-20 08:27 UTC
