### ISSUE TITLE
SOPN parsing: Blank Independent Party Candidate

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#886] opened 2019-04-04 21:59 UTC
UPDATE (see comments below): A blank Independent party candidate is added when a name can't be found. 
![Screen Shot 2021-04-01 at 12 24 06 PM](https://user-images.githubusercontent.com/7017118/113295536-3ab9e600-92f0-11eb-8a15-475c8c452d94.png)

> Independent Community and Health Concern candidates are getting split by the SOPN parser, with the name on one row and "Independent" on another : https://candidates.democracyclub.org.uk/bulk_adding/sopn/local.wyre-forest.2019-05-02/DIW:E05010502/

**Comment by VirginiaDooley** [comment] 2021-03-22 11:38
@symroe I'm not able to reproduce this issue.

**Comment by symroe** [comment] 2021-03-22 19:24
Ok thanks for testing! Similar to #889, could you work up a test for this case? The more tests we have for this stuff the better.

**Comment by VirginiaDooley** [comment] 2021-03-31 09:25
The issue now is that the Independent Community and Health Concern party is not getting parsed at all. I'll update and work on it.

**Comment by VirginiaDooley** [comment] 2021-03-31 13:02
@symroe I've stepped through every line of code in `parse_tables.py` several times. I initially thought it was an issue related to having 'Independent' in the name but that's not it. The parsing command is extracting the correct party and returning it as it should. Then I found this which I think is the same bug? https://github.com/DemocracyClub/yournextrepresentative/issues/1367

**Comment by VirginiaDooley** [comment] 2021-04-01 11:48
After discussing with Michael, we actually found that that the current code was not splitting the party, but rather adding a blank candidate with an Independent party. I'll update this issue with the blank adding problem and #1367 will be reconsidered after https://github.com/DemocracyClub/yournextrepresentative/pull/1348 is merged.

**Closed** 2021-04-06 09:26 UTC
Labels: SOPN PDF parsing
