### ISSUE TITLE
Unify photo upload forms

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/yournextrepresentative#2026] opened 2023-04-17 11:00 UTC
Currently,  photo url and photo file uploads are created in two separate forms. Moving the url upload functionality to the file upload form would simplify the code and grant access to photo cleaning methods, such as rotating photos.

**Comment by pmk01** [comment] 2024-08-21 10:05
Duplicate of https://github.com/DemocracyClub/yournextrepresentative/issues/250

**Comment by symroe** [comment] 2024-08-21 10:05
Duplicate of #250

**Closed** 2024-08-21 10:05 UTC
Labels: enhancement
