### ISSUE TITLE
Create Person and PersonExtra records in a transaction

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#463] opened 2018-04-03 14:00 UTC
At the moment, when we create a person, we call 

```python
person = Person.objects.create(name=person_data['name'])
person_extra = PersonExtra.objects.create(base=person)
```

each of those statements performs database IO. This means if something goes wrong, we can end up in an inconsistent state leading us to throw. `DoesNotExist PersonExtra matching query does not exist.`

What we should actually do is (terrible pseudo-code)

```
person = Person(bla bla)
person_extra = PersonExtra(bla bla)
# transaction.atomic()
person.save()
person_extra.save()
```

so we either create both records or neither.

**Comment by symroe** [comment] 2018-04-03 14:01
https://sentry.io/democracy-club-gp/ynr-v9/issues/512111676/

**Comment by symroe** [comment] 2018-04-03 14:05
It might be a good idea to do this in the `add_person` function directly, but in the case you're talking about the call to `add_person` [is already wrapped in a transaction](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/bulk_adding/views/parties.py#L210).

I don't think the exception is caused by inconsistent data at the DB level. Instead I think it's that elastic search has indexed the model with the ID assigned to the model in the transaction, and then the model has stopped existing after the transaction was rolled back. ES doesn't know about the transaction, so hasn't rolled back the index.

We can solve this, and speed things up, but adding to the search index as a batch job once all the people have been inserted (at the moment we're blocking on ES, I think)

**Closed** 2018-04-09 20:29 UTC
