### ISSUE TITLE
Ensure Celery queue is running on the YNR server

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/yournextrepresentative#1597] opened 2021-09-29 17:25 UTC
### Issue and Steps to Reproduce
From the command line, I ran: 
```

(env) yournextrepresentative % celery --app=ynr worker -l INFO 
[2021-09-29 18:02:48,699: WARNING/MainProcess] No hostname was supplied. Reverting to default 'localhost'
 
 -------------- celery@virginias-mbp.lan v5.1.2 (sun-harmonics)
--- ***** ----- 
-- ******* ---- macOS-11.6-x86_64-i386-64bit 2021-09-29 18:02:48
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         ynr:0x102b36a00
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . facebook_data.tasks.extract_fb_page_id
  . facebook_data.tasks.get_ads_for_page
  . facebook_data.tasks.save_advert_image
  . moderation_queue.slack.post_action_to_slack
  . sopn_parsing.tasks.extract_and_parse_tables_for_ballot

[2021-09-29 18:02:49,682: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds... (1/100)
```

**Comment by symroe** [comment] 2022-10-26 11:54
Dupe of https://github.com/DemocracyClub/yournextrepresentative/issues/734

**Closed by symroe** 2022-10-26 11:54 UTC
