### ISSUE TITLE
Javascript errors when trying to add a candidate

### ISSUE THREAD

**Issue by xavriley** [DemocracyClub/yournextrepresentative#102] opened 2017-04-19 08:41 UTC
I'm receiving the following errors in Chrome developer tools when trying to add a new candidate to Bristol West:

https://candidates.democracyclub.org.uk/election/parl.2017-06-08/post/WMC:E14000602/bristol-west
```
all.b85c78f532e6.js:26 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ all.b85c78f532e6.js:26

all.b85c78f532e6.js:451 Uncaught TypeError: $(...).not(...).not(...).select2 is not a function
    at k (all.b85c78f532e6.js:451)
    at Object.success (all.b85c78f532e6.js:451)
    at cf (all.b85c78f532e6.js:26)
    at Object.fireWith [as resolveWith] (all.b85c78f532e6.js:26)
    at co (all.b85c78f532e6.js:26)
    at XMLHttpRequest.cf (all.b85c78f532e6.js:26)

VM533:451 Uncaught TypeError: $(...).not(...).not(...).select2 is not a function
    at k (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:451:181344)
    at Object.eval [as success] (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:451:183083)
    at cf (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:26:26306)
    at Object.fireWith [as resolveWith] (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:26:27315)
    at co (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:26:93222)
    at XMLHttpRequest.cf (eval at <anonymous> (all.b85c78f532e6.js:15), <anonymous>:26:97769)
```

The information I'm trying to add is as follows:

```
Full name: Sarah Margaret 'Molly' Scott Cato
Email: office@mollymep.org.uk
Party in 2017 General Election: Green Party
Add new election: 2017 General Election (2017-06-08)
```

(source: http://www.bristolgreenparty.org.uk/bristol-green-party-announce-parliamentary-candidates)

Shortly after selecting from the "add new election" dropdown I see what appears to be a version of the full page being rendered, as if the response was expecting a HTML snippet but was instead loading a full page layout. This seems to match up with what the Network tab is showing:

![](https://www.dropbox.com/s/unuvcfhfsidarav/Screenshot%202017-04-19%2009.39.52.png?dl=1)

I've managed to replicate this in a private browsing window. My first thought was the quotation marks in the name but I've tried all variations of those and the issue persists. Please let me know if there's anything else I can do to help.

**Comment by andylolz** [comment] 2017-04-20 11:46
Thanks, @xavriley! It does sound like there’s a bug here. But in this specific case, I’m not sure why you would be selecting from the “add new election” dropdown, since Molly is already listed as a candidate… Were you editing the existing candidate (i.e. here: https://candidates.democracyclub.org.uk/person/34111) or adding a new one?

**Comment by andylolz** [comment] 2017-04-20 11:49
Oh! Apologies – I suspect she wasn’t listed as a candidate when you were working on this. My mistake!

Yes, so there’s some javascript that loads the list of parties to choose from… I think @symroe was working on changing that at around the time you posted this issue, so it’s possible that was the cause! Have you hit this error since?

**Comment by symroe** [comment] 2018-11-06 13:55
I'm fairly sure this is fixed now – I expect it was an error with deployment at one point, but we've had no more reports of this in a couple of years…and loads of new candidates!

**Closed by symroe** 2018-11-06 13:55 UTC
