### ISSUE TITLE
creating an account from trying to edit a person doesn't return you to that page

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#182] opened 2017-05-09 10:35 UTC
There are lots of points of friction in the login process, but this is perhaps the worst one: it comes up in Joe R's Facebook video for example. If you're not logged in, but are on a candidate's page and click "Log in to edit", the page to return to is recorded in the `?next=/person/34582/teck-khong` parameter. If you then click "Create Account", then you go to a "Sign Up" page (which still preserves that `next` parameter).

Once you click "Sign Up", however, you get a page saying "Verfiy Your E-mail Address". The confirmation email includes a confirmation link, but doesn't include anything about the next page to go to. (Also, a thing to note that we've seen in other usability testing is that people will often click "Confirm" on another device anyway.)

Clicking confirm¹ on the page that the confirmation link takes you to takes you back to the sign-in page (again perhaps unnecessary?) but without the `next` parameter. Signing in then takes you to the page where you have to agree to assign copyright and then you get taken to the home page.

This flow is worse because it's email sign-up, and not a social login mechanism that doesn't need the email confirmation step, but still not being taken back to where you were after this lengthy series of steps is really bad.

This process is handled by django-allauth so some parts may be difficult to customize, but I would think that we could (for example) store the page that first required login in the session, and redirect to that after someone's agreed to the copyright assignment.

¹ another non-obvious step you have to take...

**Comment by VirginiaDooley** [comment] 2021-10-07 14:27
I can't reproduce this issue. @symroe why was this added after closing?

**Closed** 2021-10-20 10:04 UTC
Labels: login, size-medium, priority: high
