### ISSUE TITLE
EE importer attaching posts incorrectly

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#929] opened 2019-04-10 15:53 UTC
There are two wards with the same ID but slightly different names:
`local.surrey-heath.st-michaels.2019-05-02` - [Surrey Heath, St Michaels](https://elections.democracyclub.org.uk/elections/local.surrey-heath.st-michaels.2019-05-02/)
`local.allerdale.st-michaels.2019-05-02` - [Allerdale, St Michael's](https://elections.democracyclub.org.uk/elections/local.allerdale.st-michaels.2019-05-02/)

When the CSV files are generated, it seems to pick up the same spelling for both posts. Which spelling it uses appears to be random (because the order of the CSV appears to be random?)

e.g. https://candidates.democracyclub.org.uk/media/candidates-2019-05-02.csv

At 10:03 today it had **St Michaels** for all candidates in both wards:

```
	Line 21717: 29592,Flic Crowley,,,,,local.allerdale.2019-05-02,party:63,Green Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP63,,False
	Line 21776: 53753,Diane Carter,,,,,local.allerdale.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 21777: 53754,Arwen Tuck,,,,,local.allerdale.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 21815: 54592,Mary Elizabeth Bainbridge,,,Female,,local.allerdale.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michaels,,,,,,,,,,,https://static-candidates.democracyclub.org.uk/media/images/images/54592.png,,profile-photo,brycx,https://democracy.allerdale.gov.uk/mgUserInfo.aspx?UID=808,,2019-05-02,True,False,,,,,,PP53,,False
	Line 21816: 54593,Billy Miskelly,,,Male,,local.allerdale.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michaels,,,,,,,,,,,https://static-candidates.democracyclub.org.uk/media/images/images/54593.png,,profile-photo,brycx,https://democracy.allerdale.gov.uk/mgUserInfo.aspx?UID=809,,2019-05-02,True,False,,,,,,PP53,,False
	Line 21836: 54687,Will Wilkinson,,,,,local.allerdale.2019-05-02,ynmp-party:2,Independent,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,ynmp-party:2,,False
	Line 24425: 32147,Jill Coles,,,,,local.surrey-heath.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP53,,False
	Line 24428: 32153,Richard Dean Claridge,,,,,local.surrey-heath.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP53,,False
	Line 24435: 63829,Colin Stanley Robertson Dougan,,,,,local.surrey-heath.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 24436: 63830,Alan Mcclafferty,,,,,local.surrey-heath.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michaels,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
```

At 16:27 the wards had swapped around, and both wards were named **St Michael's**:

```
	Line 14: 32147,Jill Coles,,,,,local.surrey-heath.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP53,,False
	Line 17: 32153,Richard Dean Claridge,,,,,local.surrey-heath.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP53,,False
	Line 24: 63829,Colin Stanley Robertson Dougan,,,,,local.surrey-heath.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 25: 63830,Alan McClafferty,,,,,local.surrey-heath.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 5667: 29592,Flic Crowley,,,,,local.allerdale.2019-05-02,party:63,Green Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP63,,False
	Line 5726: 53753,Diane Carter,,,,,local.allerdale.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 5727: 53754,Arwen Tuck,,,,,local.allerdale.2019-05-02,party:52,Conservative and Unionist Party,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,PP52,,False
	Line 5765: 54592,Mary Elizabeth Bainbridge,,,Female,,local.allerdale.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michael's,,,,,,,,,,,https://static-candidates.democracyclub.org.uk/media/images/images/54592.png,,profile-photo,brycx,https://democracy.allerdale.gov.uk/mgUserInfo.aspx?UID=808,,2019-05-02,True,False,,,,,,PP53,,False
	Line 5766: 54593,Billy Miskelly,,,Male,,local.allerdale.2019-05-02,party:53,Labour Party,DIW:st-michaels,St Michael's,,,,,,,,,,,https://static-candidates.democracyclub.org.uk/media/images/images/54593.png,,profile-photo,brycx,https://democracy.allerdale.gov.uk/mgUserInfo.aspx?UID=809,,2019-05-02,True,False,,,,,,PP53,,False
	Line 5786: 54687,Will Wilkinson,,,,,local.allerdale.2019-05-02,ynmp-party:2,Independent,DIW:st-michaels,St Michael's,,,,,,,,,,,,,,,,,2019-05-02,True,False,,,,,,ynmp-party:2,,False
```
This also affects other wards, e.g. St Pauls (Surrey Heath) and St Paul's (Tendring)

**Comment by chris48s** [comment] 2019-04-10 18:25
Just to clarify - this is just a sorting problem? We're getting the same data, but the order of the rows is non-deterministic?

**Comment by sjorford** [comment] 2019-04-10 19:41
Not just the sort order - the data is different. Look at the spelling of "St Michael(')s" in the two examples.

**Comment by symroe** [comment] 2019-04-16 18:53
This is actually a problem with the way we're importing posts from EveryElection in to YNR.

The code assumes (wrongly) that post IDs are globally unique, rather than unique to the organisation. This means that it's assuming `DIW:st-michaels` in Allerdale _is the same place_ as the one in Surrey Heath.

This woulnd't happen if we could use GSS or some other globally unique ID.

The solution is to create posts per organisation, not globally.

I'll try to work on a regression test for this.

**Comment by chris48s** [comment] 2019-04-16 19:18
You may already be way ahead on this, but in EE we're prefixing the slugs, so to make a unique id, so we've got `SUR:st-michaels` and `ALL:st-michaels` instead of `DIW:st-michaels` and `DIW:st-michaels`. See

* https://elections.democracyclub.org.uk/api/elections/local.surrey-heath.st-michaels.2019-05-02/
* https://elections.democracyclub.org.uk/api/elections/local.allerdale.st-michaels.2019-05-02/

Dunno if replicating that here would help or break other things in this case.

Happy to talk about it tomorrow if it helps.

**Comment by chris48s** [comment] 2019-04-16 19:19
I wonder how many `DIW:castle`s and `DIW:abbey`s we have :scream_cat:

**Comment by symroe** [comment] 2019-04-16 19:24
The good news is that since moving to ballots as the key for most things, the problems are very limited. 

That being said... 

I expect this might have caused the "previous candidates" / "not standing" lists to be wrong, and that in turn might be the cause of some of the merge / revert problems we've seen this year but not previous years. (I'd assumed it was the new merge code, but I'm suspecting this more now).

**Comment by chris48s** [comment] 2019-04-16 19:34
> The good news is that since moving to ballots as the key for most things, the problems are very limited.

Silver linings :cloud: 

I guess the other thing that probably limits the scope of this is that we're only using slugs in cases where there have been recent boundary changes. In many/most cases, we have a GSS which is unique.

**Closed** 2019-04-27 07:06 UTC
