### ISSUE TITLE
Enable easier photo uploads

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#91] opened 2017-04-12 18:49 UTC
Currently the only option for photo uploads is to select an image from your local storage using a "Choose file" system.

Ideally there would also be options to:
Paste an image from your clipboard directly into the browser
Enter the URL of an online image so DC wgets it, saving users the trouble of downloading/saving then finding then uploading. (can you tell I've done that too many times already?)

**Comment by symroe** [comment] 2018-11-05 20:18
This has been done, but we can still improve it by combining the forms in to a single form, and using a "droppable" JS thingy to allow dragging photos on to the form (this is becoming a standard pattern)

**Comment by pmk01** [comment] 2024-08-21 10:06
Duplicate of https://github.com/DemocracyClub/yournextrepresentative/issues/91

**Closed by pmk01** 2024-08-21 10:06 UTC
Labels: 📷 Photo Uploader
