### ISSUE TITLE
Mobile redirect to elections2.democracyclub.org.uk

### ISSUE THREAD

**Issue by hugovk** [DemocracyClub/yournextrepresentative#180] opened 2017-05-09 05:36 UTC
After uploading an image, I got a mail like this:

> Subject: Democracy Club Candidates image upload approved
> 
> Thank-you for submitting a photo to Democracy Club Candidates;
that's been uploaded now for the candidate page here:
>
>  http://candidates.democracyclub.org.uk/person/34556/rachael-shah
>
>Many thanks from the Democracy Club Candidates volunteers

The link works on desktop (Mac, Gmail), but when opening it on Android from Gmail or Inbox into Chrome, it redirects to https://elections2.democracyclub.org.uk/person/34556/rachael-shah which says "This is not the page you were looking for." with an Every Election header rather than Democracy Club Candidates.

---

Side issue: the link could be written with https now that is also enabled.

---

Another side issue: And write "Thank you" rather than "Thank-you" as a noun ("we said our thank-yous") or attributive noun-modifier ("we sent a thank-you note")

**Comment by symroe** [comment] 2018-03-20 08:24
I think this is fixed now... It was caused by having to move things about quickly before the general election last year. Thanks!

**Closed by symroe** 2018-03-20 08:24 UTC
