### ISSUE TITLE
Reverting to an earlier version results in 500 error

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#1001] opened 2019-08-20 09:15 UTC
For this chap: https://candidates.democracyclub.org.uk/person/13423

(Attempted to revert from version 1e09ae61ece9123c to version 08add4489856f623. Have created version 7a2477cab73be411 instead)

**Comment by chris48s** [comment] 2019-08-20 10:29
Additional info: the error thrown was: `UnsafeToDelete: Trying to delete a Membership (pk=166946) that other objects that depend on`.

**Comment by symroe** [comment] 2019-08-22 07:59
The error here is related (but not a duplicate of) #819. There is a `CandidateResult` (votes cast for an ballot) object for this person. 

The way the revert process works is to delete _everything_ about a person and remake everything based on the `versions` data that's presented on the person pages.

It's quite a neat way of reverting changes, but does require that everything that gets reverted to be included in the `versions` data, and that in turn means changing the versions data for everyone, every time we add a new field. We don't currently do this, and that's why we see odd things like `Removed image, previously was null` in the history.

That aside, it's possible to just re-create the missing models manually, side-stepping the `versions` dict.

This raises an interesting question:

Do we want the revert process to remove result data? What would that mean for the other results on that ballot? Is it a way of indicating that the results were wrong?

We might want to remove the ability to revert changes once results are entered for someone (you can change results elsewhere). That is, the oldest version you can revert back to is the one where the latest results were entered. Doing otherwise would cause inconsistencies.

To be clear: it's currently not possible to revert anyone with results entered, regardless of the version, but I don't want to fix that and introduce a new set of problems.

**Closed** 2019-11-06 21:57 UTC
