### ISSUE TITLE
Images no longer show on post pages

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#626] opened 2018-08-29 11:04 UTC
e.g. https://candidates.democracyclub.org.uk/election/local.sevenoaks.2018-08-30/post/DIW:E05005016/farningham-horton-kirby-and-south-darenth

![image](https://user-images.githubusercontent.com/10633357/44783849-94c7fd00-ab83-11e8-8d0a-89ca48627fa8.png)

![image](https://user-images.githubusercontent.com/10633357/44783855-9a254780-ab83-11e8-916b-b47f262fbfa6.png)

**Comment by symroe** [comment] 2018-08-30 08:31
Note to self: This is caused by some missing `.extra` calls in:

https://github.com/DemocracyClub/yournextrepresentative/blob/b769fff66ab8315fd89757622a0387155649e9b0/ynr/apps/candidates/templates/candidates/_person_in_list.html#L7-L12

This wasn't caught in #548, so I need to write some tests for that condition.

I'll address this after #621 is merged, as I don't want to do any other work that I'll have to rebase over a PR that changes that much.

**Closed** 2018-08-31 09:57 UTC
Labels: 4 - Awaiting Review
